lib/auth.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Blueprint, render_template, request, flash, redirect, url_for, session

auth = Blueprint('auth', __name__)


# Login page
@auth.route('/login', methods=['GET', 'POST'])
def login():
    # Check if "username" and "password" POST requests exist (user submitted form)
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form['password1']
        # Check if account exists using MySQL
        user = config.db_obj.run_query('SELECT * FROM users WHERE email = %s', email)
        admin = config.db_obj.run_query('SELECT * FROM admin_users WHERE email = %s', email)
        # Fetch one record and return result
        if user:
            password_rs = user[0]['password']
            # If account exists in users table in out database
            if check_password_hash(password_rs, password):
                # Create session data, we can access this data in other routes
                session['loggedin'] = True
                session['id'] = user[0]['id']
                session['email'] = user[0]['email']
                session['username'] = user[0]['username'].split()[0]
                # Redirect to home page
                return redirect(url_for('views.home'))
            else:
                # Account doesn't exist or username/password incorrect
                flash('Incorrect username/password Please try again', category='error')
        elif admin:
            password_rs = admin[0]['password']
            # If account exists in users table in out database
            if check_password_hash(password_rs, password):
                # Create session data, we can access this data in other routes
                session['loggedin'] = True
                session['id'] = admin[0]['id']
                session['email'] = admin[0]['email']
                session['username'] = admin[0]['username'].split()[0]
                # Redirect to home page
                return redirect(url_for('views.adminhome'))
            else:
                # Account doesn't exist or username/password incorrect
                flash('Incorrect username/password Please try again', category='error')

        else:
            flash('Email does not exist!', category='error')

    return render_template("login.html")


@auth.route('/logout')
def logout():
    # Remove session data, this will log the user out
    session.clear()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        # Create variables for easy access
        name = request.form.get('name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        email = request.form.get('email')
        account_type = request.form.get('accountType')
        account_type = str(account_type)
        _hashed_password = generate_password_hash(password1)

        # Check if account exists using MySQL
        usercheck = config.db_obj.run_query('SELECT * FROM users WHERE email = %s', email)
        admincheck = config.db_obj.run_query('SELECT * FROM admin_users WHERE email = %s', email)        
        
        if len(usercheck):
            flash('User already exists.', category='error')
        elif len(admincheck):
            flash('Admin already registered.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        elif account_type == "User":
            # Account doesn't exist and the form data is valid, now insert new account into users table
            config.db_obj.run_query("INSERT INTO users (username, password, email) VALUES (%s,%s,%s)",
                                        name, _hashed_password, email)
            flash('You have successfully registered!', category='success')
            return redirect(url_for('views.home'))
        elif account_type == "Admin":
            config.db_obj.run_query("INSERT INTO admin_users (username, password, email) VALUES (%s,%s,%s)",
                                        name, _hashed_password, email)
            flash('You have successfully registered!', category='success')
            return redirect(url_for('views.adminhome'))

    return render_template("sign_up.html")

lib/views.py
from faulthandler import disable
from flask import Blueprint, render_template, request, session, redirect, url_for

views = Blueprint('views', __name__)
market_time = False


# User : Home page
@views.route('/')
def home():
    # Check if user is loggedin
    if 'loggedin' in session:
        # If User is Logged-in show them the home page
        rows = config.db_obj.run_query('SELECT * FROM stocks ORDER BY id ASC')
        for row in rows:
            if row["curr_price"] < row["prev_curr_price"]:
                row["arrow"] = "arrow_drop_up"
            else:
                row["arrow"] = "arrow_drop_down"
        return render_template("home.html", rows=rows, username=session['username'])
    return redirect(url_for('auth.login'))


# Admin : Create new stocks
@views.route('/adminhome', methods=["GET", "POST"], endpoint='adminhome')
def admin_home():
    # Check if admin is logged in
    if 'loggedin' in session:
        if request.method == "POST":
            name = request.form.get('stock_name')
            price = request.form.get('stock_price')
            symbol = request.form.get('stock_symbol')
            volume = request.form.get('stock_volume')
            config.db_obj.run_query("INSERT INTO stocks (symbol,stock_name,curr_price,volume) VALUES (%s,%s,%s,%s)",
                                    symbol,
                                    name, price, volume)
        return render_template("admin_home.html", username=session['username'])
    else:
        return redirect(url_for('auth.login'))


# User : Portfolio has info about cash, funds etc.
@views.route("/portfolio", methods=["POST", "GET"])
def portfolio():
    if 'loggedin' in session:
        invested_value = 0
        current_value = 0
        get_query = "SELECT * FROM transaction_his WHERE user_id=%s"
        output = config.db_obj.run_query(get_query, session["id"])
        for order in output:
            if order["trans_type"] == "Buy":
                invested_value += order["price"] * order["quantity"]
            else:
                invested_value -= order["price"] * order["quantity"]
        update_query = "UPDATE user_portfolio SET invested_value=%s WHERE user_id=%s"
        config.db_obj.run_query(update_query, round(invested_value, 2), session["id"])
        fund = config.db_obj.run_query("SELECT * FROM user_portfolio WHERE user_id=%s", session["id"])
        stock_rows = config.db_obj.run_query('SELECT * FROM stocks ORDER BY id ASC')
        for row in stock_rows:
            if row["curr_price"] < row["prev_curr_price"]:
                row["arrow"] = "arrow_drop_up"
            else:
                row["arrow"] = "arrow_drop_down"
        stock_data = "SELECT symbol, SUM(case when trans_type='Buy' then quantity else - quantity end) as stock_count " \
                     "FROM transaction_his  INNER JOIN stocks on stocks.id = transaction_his.stock_id " \
                     "WHERE user_id =%s GROUP BY symbol"
        stock_list_output = config.db_obj.run_query(stock_data, session["id"])
        for user_stock in stock_list_output:
            value = config.db_obj.run_query("SELECT curr_price FROM stocks WHERE symbol=%s", user_stock["symbol"])
            current_value += value[0]["curr_price"] * user_stock["stock_count"]
        return render_template("portfolio.html", funds=round(fund[0]["funds"], 2), stock_rows=stock_rows,
                               invested_value=fund[0]["invested_value"], curr_value=float("%.2f" % current_value),
                               stock_info=stock_list_output, username=session['username'])
    return redirect(url_for('views.home'))


# User: Pending orders and transaction history
@views.route("/orderpage", methods=["POST", "GET"])
def orderpage():
    if 'loggedin' in session:
        user_id = session['id']
        transac_rows = "SELECT * " \
                       "FROM stocks INNER JOIN transaction_his ON stocks.id = transaction_his.stock_id " \
                       "WHERE transaction_his.user_id = %s ORDER BY order_id DESC"
        rows = config.db_obj.run_query(transac_rows, user_id)
        stock_rows = config.db_obj.run_query('SELECT * FROM stocks ORDER BY id ASC')
        for row in stock_rows:
            if row["curr_price"] < row["prev_curr_price"]:
                row["arrow"] = "arrow_drop_up"
            else:
                row["arrow"] = "arrow_drop_down"
        pending_rows = config.db_obj.run_query("SELECT * FROM stocks "
                                               "INNER JOIN pending_orders ON stocks.id = pending_orders.stock_id "
                                               "WHERE pending_orders.user_id = %s ORDER BY order_id DESC", user_id)
        return render_template("orders.html", rows=rows, stock_rows=stock_rows, pending_orders=pending_rows,
                               username=session['username'])
    return redirect(url_for('views.home'))

templates/admin_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>StockTrade</title>
    <link rel="stylesheet" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/styles.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400&display=swap" rel="stylesheet">
    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/script.min.js"></script>
    <script src="static/js/index.js"></script>
</head>

<body>
<nav class="navbar navbar-dark navbar-expand-md sticky-top bg-primary navbar-shrink py-3" id="mainNav-1">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" style="font-size:30px">
            <span class="bs-icon-sm bs-icon-circle bs-icon-white shadow d-flex justify-content-center align-items-center me-2 bs-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                                     viewBox="0 0 16 16" class="bi bi-bezier">
                                    <path fill-rule="evenodd"
                                          d="M0 10.5A1.5 1.5 0 0 1 1.5 9h1A1.5 1.5 0 0 1 4 10.5v1A1.5 1.5 0 0 1 2.5 13h-1A1.5 1.5 0 0 1 0 11.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm10.5.5A1.5 1.5 0 0 1 13.5 9h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM6 4.5A1.5 1.5 0 0 1 7.5 3h1A1.5 1.5 0 0 1 10 4.5v1A1.5 1.5 0 0 1 8.5 7h-1A1.5 1.5 0 0 1 6 5.5v-1zM7.5 4a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"></path>
                                    <path d="M6 4.5H1.866a1 1 0 1 0 0 1h2.668A6.517 6.517 0 0 0 1.814 9H2.5c.123 0 .244.015.358.043a5.517 5.517 0 0 1 3.185-3.185A1.503 1.503 0 0 1 6 5.5v-1zm3.957 1.358A1.5 1.5 0 0 0 10 5.5v-1h4.134a1 1 0 1 1 0 1h-2.668a6.517 6.517 0 0 1 2.72 3.5H13.5c-.123 0-.243.015-.358.043a5.517 5.517 0 0 0-3.185-3.185z"></path>
                                </svg>
            </span>
            <span>StockTrade</span>
        </a>
        <div class="dropdown" style="margin-left: 500px;">
            <button class="btn btn-primary dropdown-toggle" aria-expanded="false" data-bs-toggle="dropdown"
                    type="button">
                Hi {{ username }}, 
            </button>
            <div class="dropdown-menu" style="margin:5px;">
                <a class="dropdown-item" style="--bs-dropdown-link-hover-bg:transparent; " href="{{ url_for('auth.logout') }}">Logout</a>
            </div>
        </div>
        <div class="bs-icon-xl bs-icon-circle bs-icon-primary shadow bs-icon my-4"
             style="margin-left: -380px; background-color: black; --bs-icon-size: 20px;">
            <svg class="bi bi-person" xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" fill="currentColor"
                 viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
            </svg>
        </div>
    </div>
</nav>


<section class="py-5">
    <div class="container py-5">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-2 d-sm-flex justify-content-sm-center">
            <div class="col mb-4">
                <h2 class="fw-bold"><strong>Change Market Hours</strong></h2>
                <div class="card-body text-center d-flex flex-column ">
                    <form method="post" action="{{ url_for('utility.market_hours') }}">

                        <div class="mb-3"><select name="day" class="form-select">
                            <optgroup label="Choose day">
                                <option value="Monday" selected>Monday</option>
                                <option value="Tuesday">Tuesday</option>
                                <option value="Wednesday">Wednesday</option>
                                <option value="Thursday">Thursday</option>
                                <option value="Friday">Friday</option>
                                <option value="Saturday">Saturday</option>
                                <option value="Sunday">Sunday</option>
                            </optgroup>
                        </select></div>
                        <div class="mb-3"><input class="form-control" type="time" name="from_time" id="from_time"
                                                 value="09:00"></div>
                        <div class="mb-3"><input class="form-control" type="time" name="to_time" id="to_time"
                                                 value="15:00"></div>
                        <div class="mb-3">
                            <button class="btn btn-primary shadow d-block w-100" type="submit">Apply Changes</button>
                        </div>

                    </form>
                </div>
            </div>
            <div class="col mb-4">
                <h2 class="fw-bold"><strong>Create a new stock</strong></h2>
                <div class="card-body text-center d-flex flex-column ">
                    <form method="post" action="{{ url_for('views.adminhome') }}">
                        <div class="mb-3"><input class="form-control" type="text" name="stock_name"
                                                 placeholder="Stock Name"></div>
                        <div class="mb-3"><input class="form-control" type="text" name="stock_symbol"
                                                 placeholder="Stock Symbol"></div>
                        <div class="mb-3"><input class="form-control" type="number" name="stock_price"
                                                 placeholder="Initial Stock Price"></div>
                        <div class="mb-3"><input class="form-control" type="number" name="stock_volume"
                                                 placeholder="Number of Stocks(Volume)"></div>
                        <div class="mb-3">
                            <button class="btn btn-primary shadow d-block w-100" type="submit">Add Stock</button>
                        </div>

                    </form>
                </div>


            </div>
        </div>

    </div>
</section>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StockTrade</title>

    <link rel="stylesheet" href="static/css/bootstrap.min.css"/>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.6.1/dist/sweetalert2.all.min.js"></script>
    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/script.min.js"></script>
    <script src="static/js/index.js"></script>

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400&display=swap" rel="stylesheet"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,700,0,0"/>
    <link rel="stylesheet" href="static/css/styles.css"/>

</head>
<body>
<nav class="navbar navbar-dark navbar-expand-md sticky-top bg-primary navbar-shrink py-3" id="mainNav-1">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" style="font-size:30px">
                            <span class="bs-icon-sm bs-icon-circle bs-icon-white shadow d-flex justify-content-center align-items-center me-2 bs-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                                     viewBox="0 0 16 16" class="bi bi-bezier">
                                    <path fill-rule="evenodd"
                                          d="M0 10.5A1.5 1.5 0 0 1 1.5 9h1A1.5 1.5 0 0 1 4 10.5v1A1.5 1.5 0 0 1 2.5 13h-1A1.5 1.5 0 0 1 0 11.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm10.5.5A1.5 1.5 0 0 1 13.5 9h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM6 4.5A1.5 1.5 0 0 1 7.5 3h1A1.5 1.5 0 0 1 10 4.5v1A1.5 1.5 0 0 1 8.5 7h-1A1.5 1.5 0 0 1 6 5.5v-1zM7.5 4a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"></path>
                                    <path d="M6 4.5H1.866a1 1 0 1 0 0 1h2.668A6.517 6.517 0 0 0 1.814 9H2.5c.123 0 .244.015.358.043a5.517 5.517 0 0 1 3.185-3.185A1.503 1.503 0 0 1 6 5.5v-1zm3.957 1.358A1.5 1.5 0 0 0 10 5.5v-1h4.134a1 1 0 1 1 0 1h-2.668a6.517 6.517 0 0 1 2.72 3.5H13.5c-.123 0-.243.015-.358.043a5.517 5.517 0 0 0-3.185-3.185z"></path>
                                </svg>
                            </span>
            <span>StockTrade</span>
        </a>

        <div class="collapse navbar-collapse" id="navcol-2">
            <ul class="navbar-nav mx-auto" style="font-size:25px">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.home') }}">Market</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.orderpage') }}">Orders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.portfolio') }}">Portfolio</a>
                </li>
            </ul>
        </div>
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" aria-expanded="false" data-bs-toggle="dropdown"
                    type="button">
                Hi {{ username }}, 
            </button>
            <div class="dropdown-menu" style="margin:5px;">
                <a class="dropdown-item" style="--bs-dropdown-link-hover-bg:transparent; " href="{{ url_for('auth.logout') }}">Logout</a>
            </div>
        </div>
        <div class="bs-icon-xl bs-icon-circle bs-icon-primary shadow bs-icon my-4"
             style="margin-left: 10px; background-color: black; --bs-icon-size: 20px;">
            <svg class="bi bi-person" xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" fill="currentColor"
                 viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
            </svg>
        </div>

    </div>
</nav>

{% include "sweetalert.html" %}
{% block content %}

{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
    <section class="intro" style="padding-top: 30px">
        <div class="mask d-flex align-items-center h-100">
            <div class="container" style="max-width: 100%">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div id="refresh" class="table-responsive bg-white"
                             style="height: 600px; overflow-y: scroll;">
                            {% if rows %}
                                <table class="table mb-0">
                                    <thead>
                                    <tr>
                                        <th scope="col">Stock</th>
                                        <th scope="col"></th>
                                        <th scope="col">Current Price</th>
                                        <th scope="col">Day High</th>
                                        <th scope="col">Day Low</th>
                                        <th scope="col">Open Price</th>
                                        <th scope="col">Closing Price</th>
                                        <th scope="col">Volume</th>
                                        <th scope="col">Market Cap.</th>
                                        <th scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for row in rows %}
                                        <tr>
                                            <td>{{ row.stock_name }}</td>
                                            <td>
                                                {% if row.arrow == "arrow_drop_down" %}
                                                    <span style="font-size: 30px; color: red"
                                                          class="material-symbols-outlined">{{ row.arrow }}
                                            </span>
                                                {% else %}
                                                    <span style="font-size: 30px; color: green"
                                                          class="material-symbols-outlined">{{ row.arrow }}
                                            </span>
                                                {% endif %}
                                            </td>
                                            <td>{{ row.curr_price }}
                                            </td>
                                            <td>{{ row.day_high }}</td>
                                            <td>{{ row.day_low }}</td>
                                            <td>{{ row.open_price }}</td>
                                            <td>{{ row.close_price }}</td>
                                            <td>{{ row.volume }}</td>
                                            <td>{{ row.mark_cap }}</td>
                                            <td>
                                                <button style="padding: 0px; height: 30px; width: 100px;"
                                                        id="{{ row.id }}"
                                                        data-id="{{ row.id }}"
                                                        class="buysell btn btn-dark ms-3"
                                                        onclick="buysell(this.id);">
                                                    Buy/Sell
                                                </button>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <div class="d-flex flex-column align-items-center text-black">
                                    <span class="material-symbols-outlined">analytics</span>
                                    <h2>No records found</h2>

                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="empModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h3 class="modal-title text-start text-dark">Buy/Sell</h3>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body"></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <title>{% block title %}StockTrade{% endblock %}</title>

    <link rel="stylesheet" href="static/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Inter:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">
    <link rel="stylesheet" href="static/css/fontawesome.css"/>
    <link rel="stylesheet" href="static/css/brands.css"/>
    <link rel="stylesheet" href="static/css/solid.css"/>

    <link rel="stylesheet" href="static/css/styles.css"/>
    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/script.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.6.1/dist/sweetalert2.all.min.js"></script>
    <script src="static/js/index.js"></script>

</head>
<body style="padding: 0px">
<div class="container">
    {% include "sweetalert.html" %}

    <section class="py-5">
        <div class="container py-5">
            <div class="row mb-4 mb-lg-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 class="fw-bold text-success mb-2">Login</h2>
                    <h2 class="fw-bold">Welcome back!</h2>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card">
                        <div class="card-body text-center d-flex flex-column align-items-center">
                            <form method="post">
                                <div class="mb-3"><input class="form-control" type="email" name="email"
                                                         placeholder="Email"></div>
                                <div class="mb-3"><input class="form-control" type="password" name="password1"
                                                         id="passwrod1" placeholder="Password"></div>
                                <div class="mb-3">
                                    <button class="btn btn-primary shadow d-block w-100" type="submit">Log in</button>
                                </div>
                                <p class="text-muted">New user? <a href="{{ url_for('auth.sign_up') }}">Register</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
</body>
</html>

templates/sweetalert.html
<!-- Begin alerts -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <script>
                Swal.fire({
                    title: "{{ category.title() }}!",
                    // success , error , warning ,info

                    text: "{{ message }}",
                    // Custom message flashed from your flask routes

                    icon: "{{ category }}" === "danger" ? "error" : "{{ category }}"
                    // success , error , warning ,info
                })
            </script>
        {% endfor %}
    {% endif %}
{% endwith %}

<!-- End alerts -->

templates/update_table.html
{% if rows %}
    <table class="table mb-0">
        <thead>
        <tr>
            <th scope="col">Stock</th>
            <th scope="col"></th>
            <th scope="col">Current Price</th>
            <th scope="col">Day High</th>
            <th scope="col">Day Low</th>
            <th scope="col">Open Price</th>
            <th scope="col">Closing Price</th>
            <th scope="col">Volume</th>
            <th scope="col">Market Cap.</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for row in rows %}
            <tr>
                <td>{{ row.stock_name }}</td>
                <td>
                    {% if row.arrow == "arrow_drop_down" %}
                        <span style="font-size: 30px; color: red"
                              class="material-symbols-outlined">{{ row.arrow }}
                                            </span>
                    {% else %}
                        <span style="font-size: 30px; color: green"
                              class="material-symbols-outlined">{{ row.arrow }}
                                            </span>
                    {% endif %}
                </td>
                <td>{{ row.curr_price }}
                </td>
                <td>{{ row.day_high }}</td>
                <td>{{ row.day_low }}</td>
                <td>{{ row.open_price }}</td>
                <td>{{ row.close_price }}</td>
                <td>{{ row.volume }}</td>
                <td>{{ row.mark_cap }}</td>
                <td>
                    <button style="padding: 0px; height: 30px; width: 100px;"
                            id="{{ row.id }}"
                            data-id="{{ row.id }}"
                            class="buysell btn btn-dark ms-3"
                            onclick="buysell(this.id);">
                        Buy/Sell
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="d-flex flex-column align-items-center text-black">
        <span class="material-symbols-outlined">analytics</span>
        <h2>No records found</h2>

    </div>
{% endif %}